language: java
sudo: true
script: mvn install -f java/pro2/pom.xml
before_script:
- chmod +x update-gh-pages.sh
jdk:
- oraclejdk8
# - oraclejdk7
# - openjdk6
notifications:
  email:
    on_success: never
    on_failure: change
after_success: ./update-gh-pages.sh
env:
  global:
    secure: NXWV+lz80Y2DtFqgk3t16RCIlWkSn1zK8+nj+rk32UmzPwt7FjLZfhpm2k2TT3s0LRHsrUABtzozhkBsUDxgCI4mNn6LWnOLjnq7Svwo3GPiHH7gmwwG8y7etiEDTXnU9O+aKUnBdqOkvxmHu7MYRJwACTFau+uENwFwoY8+AjnO33XdQK1hW5L5iSYcMb0r64ehOFkALg9mDdYXnW2Kd8Bj7uexkUYeN3yeQPz0yFoxn7RsASN0OvrtJH43kkLgsOKJlifVLl6dGgE+EPNtm1TUoutiVx+XOQdFcbDxe7fO0oFpL+CPjjZK35AwseZsZsJeXvykUixMWvYy18aNQ07oFENLpUPYg0zCOZj4lhdtjZq80ftoUYZoP7V4gntxFtmuMMRcg/wnUW4yzSCdLObRv6hgIvQehgJxN5XcNlJWrl4Cio/+c/kGDVJVm8qK7x3zqmX4CsWEjfMyRwpqydkuH4Sj5i1eIqGiRe9CRArq7k2MhX1G5C3VbuRzF55s2/rKHLoDDB9t7Ul991C3iE9ZAp4uUHF0rw5b+mykEVIrtgyZ0X2umt/FXA+ns6rJ3O47g1LU7PHfid1GrClreeZfrUT39sonrTKyC+Q+if+OJEjhQ/3mGUFs66DMm79O/NxCNdF3cLW7xg12tsKVHk0BtSRjAbYelMCwTe0bVrk=
